# Generated by Django 3.2.8 on 2021-10-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BC', models.CharField(max_length=100)),
                ('Y2012', models.CharField(max_length=100)),
                ('Y2013', models.CharField(max_length=100)),
                ('Y2014', models.CharField(max_length=100)),
                ('Y2015', models.CharField(max_length=100)),
                ('Y2016', models.CharField(max_length=100)),
                ('Y2017', models.CharField(max_length=100)),
                ('Y2018', models.CharField(max_length=100)),
                ('Y2019', models.CharField(max_length=100)),
                ('Y2020', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
